name: BetterStaff
api: 5.0.0
version: 1.0.3
author: Jorgebyte
main: Jorgebyte\BetterStaff\Main

permissions:
  betterstaff.command.staff:
    default: op
  betterstaff.command.freeze:
    default: op
  betterstaff.staffchat:
    default: op
  betterstaff.command.staffchat:
    default: op
  betterstaff.command.tempban:
    default: op
  betterstaff.command.untempban:
    default: op
  betterstaff.command.playerinfo:
    default: op
  betterstaff.reportview:
    default: op
  betterstaff.stafflist:
    default: op
  betterstaff.command.report:
    default: true
  betterstaff.command.stafflist:
    default: true
